# -*- coding: utf-8 -*-
"""Author a new frame by cloning an existing one's shell.

Every frame's sidebar, top bar, tabs and section rail are generated by
tools/shell.py from tools/ia.py, so a new frame only needs its own header, note
and canvas. This clones a reference frame, swaps those three, and inserts the
result after a named frame. Run shell.py afterwards to place it in the
navigation (add its id to FRAME_IA first, or --check fails).

    from framekit import add_frame
    add_frame('screens/14-settings.html', template='brand', after='brand',
              id='brand-localization', n='44b', name='Workspace — Localization',
              route='/settings/workspace/localization', arch='A5 · form',
              note='...', canvas='<div class="v-pagehead">...</div>')
"""
import re

FRAME_OPEN = re.compile(r'<section class="vs-frame[^"]*" id="([^"]+)">')


def _frame_span(s, fid):
    m = re.search(r'<section class="vs-frame[^"]*" id="%s">' % re.escape(fid), s)
    if not m:
        raise SystemExit('no frame #%s' % fid)
    end = s.find('</section>', m.end())
    # a frame may contain nested <section> cards; balance them
    depth, i = 1, m.end()
    for t in re.finditer(r'<(/?)section\b', s[m.end():]):
        depth += -1 if t.group(1) else 1
        if depth == 0:
            end = m.end() + t.start() + len('</section>')
            break
    return m.start(), end


def _div_inner_span(s, start):
    """(inner_start, inner_end) of the <div> opening at start."""
    open_end = s.index('>', start) + 1
    depth = 1
    for t in re.finditer(r'<(/?)div\b', s[open_end:]):
        depth += -1 if t.group(1) else 1
        if depth == 0:
            return open_end, open_end + t.start()
    raise ValueError('unbalanced div')


def build(template_block, id, n, name, route, arch, note, canvas, height=None, canvas_cls='vs-canvas',
          slot=None):
    """slot: a regex for the opening <div> whose contents are replaced, for frames
    with no vs-canvas (auth and guest pages). Its opening tag is kept as is."""
    b = template_block
    b = re.sub(r'<section class="vs-frame[^"]*" id="[^"]+">',
               '<section class="vs-frame%s" id="%s">' % (' vs-frame--' + height if height else '', id), b, count=1)
    hd = ('<div class="vs-frame__hd">\n      <span class="vs-frame__n">%s</span><span class="vs-frame__name">%s</span>\n'
          '      <span class="vs-frame__route">%s</span><span class="t-meta muted">%s</span>\n    </div>'
          % (n, name, route, arch))
    a, z = re.search(r'<div class="vs-frame__hd">', b).start(), None
    _, z = _div_inner_span(b, a)
    b = b[:a] + hd + b[z + len('</div>'):]
    b = re.sub(r'<p class="vs-frame__note">.*?</p>', '<p class="vs-frame__note">\n      %s\n    </p>' % note,
               b, count=1, flags=re.S)
    if slot:
        c = re.search(slot, b)
        if not c:
            raise SystemExit('template has no slot matching %s' % slot)
        i0, i1 = _div_inner_span(b, c.start())
        return b[:i0] + '\n' + canvas + '\n          ' + b[i1:]
    c = re.search(r'<div class="vs-canvas[^"]*"[^>]*>', b)
    if c:
        i0, i1 = _div_inner_span(b, c.start())
        b = b[:c.start()] + '<div class="%s">\n%s\n            ' % (canvas_cls, canvas) + b[i1:]
    else:
        raise SystemExit('template has no vs-canvas')
    return b


def add_frame(path, template, after, **kw):
    s = open(path, encoding='utf-8').read()
    if re.search(r'id="%s"' % re.escape(kw['id']), s):
        # re-running replaces the frame rather than duplicating it
        a, z = _frame_span(s, kw['id'])
        c = s.rfind('<!--', 0, a)
        if c != -1 and s[c:a].strip().endswith('-->') and '<section' not in s[c:a]:
            a = c                                   # take the banner comment with it
        s = s[:a].rstrip() + s[z:]
    ta, tz = _frame_span(s, template)
    block = build(s[ta:tz], **kw)
    aa, az = _frame_span(s, after)
    s = s[:az] + '\n\n  <!-- ══════════════════ %s · %s ══════════════════ -->\n  ' % (kw['n'], kw['name'].upper()) + block + s[az:]
    open(path, 'w', encoding='utf-8').write(s)
    return kw['id']


# ---- dialogs ------------------------------------------------------------------
# A dialog is a real overlay marked data-layer, so tools/wtgen.py lifts it into
# the walkthrough and screens/assets/flows.js opens it from any data-open. On a
# design sheet several sit side by side in a .vs-dialogs frame.

def dialog(layer, title, body, foot, wide=True, sub=None, role='dialog'):
    return ('<div class="vs-overlay vs-overlay--modal" data-layer="%s"><div class="v-scrim"></div>'
            '<div class="v-modal%s" role="%s" aria-label="%s">'
            '<div class="v-modal__title">%s</div>%s%s<div class="v-modal__foot">%s</div></div></div>'
            % (layer, ' v-modal--wide' if wide else '', role, re.sub(r'<[^>]+>', '', title), title,
               ('<p class="v-modal__sub">%s</p>' % sub) if sub else '', body, foot))


def add_dialog_sheet(path, after, id, n, name, note, dialogs):
    """dialogs: list of (caption, dialog_html). Replaces the frame on re-run."""
    s = open(path, encoding='utf-8').read()
    if re.search(r'id="%s"' % re.escape(id), s):
        a, z = _frame_span(s, id)
        c = s.rfind('<!--', 0, a)
        if c != -1 and s[c:a].strip().endswith('-->') and '<section' not in s[c:a]:
            a = c
        s = s[:a].rstrip() + s[z:]
    tiles = ''.join('\n        <div class="vs-dialog"><div class="label">%s</div>\n          %s\n        </div>' % (cap, d)
                    for cap, d in dialogs)
    frame = ('<section class="vs-frame" id="%s">\n    <div class="vs-frame__hd">\n      <span class="vs-frame__n">%s</span>'
             '<span class="vs-frame__name">%s</span>\n      <span class="vs-frame__route">dialogs</span>'
             '<span class="t-meta muted">opened from buttons on this module’s screens</span>\n    </div>\n'
             '    <p class="vs-frame__note">\n      %s\n    </p>\n    <div class="vs-frame__box"><div class="vs-dialogs">%s\n    </div></div>\n  </section>'
             % (id, n, name, note, tiles))
    aa, az = _frame_span(s, after)
    s = s[:az] + '\n\n  <!-- ══════════════════ %s · %s ══════════════════ -->\n  ' % (n, name.upper()) + frame + s[az:]
    open(path, 'w', encoding='utf-8').write(s)
    return id
