# -*- coding: utf-8 -*-
"""Author a new frame by cloning an existing one's shell.

Every frame's sidebar, top bar, tabs and section rail are generated by
tools/shell.py from tools/ia.py, so a new frame only needs its own header, note
and canvas. This clones a reference frame, swaps those three, and inserts the
result after a named frame. Run shell.py afterwards to place it in the
navigation (add its id to FRAME_IA first, or --check fails).

    from framekit import add_frame
    add_frame('screens/14-settings.html', template='brand', after='brand',
              id='brand-localization', n='44b', name='Workspace — Localization',
              route='/settings/workspace/localization', arch='A5 · form',
              note='...', canvas='<div class="v-pagehead">...</div>')
"""
import re

FRAME_OPEN = re.compile(r'<section class="vs-frame[^"]*" id="([^"]+)">')


def _frame_span(s, fid):
    m = re.search(r'<section class="vs-frame[^"]*" id="%s">' % re.escape(fid), s)
    if not m:
        raise SystemExit('no frame #%s' % fid)
    end = s.find('</section>', m.end())
    # a frame may contain nested <section> cards; balance them
    depth, i = 1, m.end()
    for t in re.finditer(r'<(/?)section\b', s[m.end():]):
        depth += -1 if t.group(1) else 1
        if depth == 0:
            end = m.end() + t.start() + len('</section>')
            break
    return m.start(), end


def _div_inner_span(s, start):
    """(inner_start, inner_end) of the <div> opening at start."""
    open_end = s.index('>', start) + 1
    depth = 1
    for t in re.finditer(r'<(/?)div\b', s[open_end:]):
        depth += -1 if t.group(1) else 1
        if depth == 0:
            return open_end, open_end + t.start()
    raise ValueError('unbalanced div')


def build(template_block, id, n, name, route, arch, note, canvas, height=None, canvas_cls='vs-canvas'):
    b = template_block
    b = re.sub(r'<section class="vs-frame[^"]*" id="[^"]+">',
               '<section class="vs-frame%s" id="%s">' % (' vs-frame--' + height if height else '', id), b, count=1)
    hd = ('<div class="vs-frame__hd">\n      <span class="vs-frame__n">%s</span><span class="vs-frame__name">%s</span>\n'
          '      <span class="vs-frame__route">%s</span><span class="t-meta muted">%s</span>\n    </div>'
          % (n, name, route, arch))
    a, z = re.search(r'<div class="vs-frame__hd">', b).start(), None
    _, z = _div_inner_span(b, a)
    b = b[:a] + hd + b[z + len('</div>'):]
    b = re.sub(r'<p class="vs-frame__note">.*?</p>', '<p class="vs-frame__note">\n      %s\n    </p>' % note,
               b, count=1, flags=re.S)
    c = re.search(r'<div class="vs-canvas[^"]*">', b)
    if c:
        i0, i1 = _div_inner_span(b, c.start())
        b = b[:c.start()] + '<div class="%s">\n%s\n            ' % (canvas_cls, canvas) + b[i1:]
    else:
        raise SystemExit('template has no vs-canvas')
    return b


def add_frame(path, template, after, **kw):
    s = open(path, encoding='utf-8').read()
    if re.search(r'id="%s"' % re.escape(kw['id']), s):
        # re-running replaces the frame rather than duplicating it
        a, z = _frame_span(s, kw['id'])
        c = s.rfind('<!--', 0, a)
        if c != -1 and s[c:a].strip().endswith('-->') and '<section' not in s[c:a]:
            a = c                                   # take the banner comment with it
        s = s[:a].rstrip() + s[z:]
    ta, tz = _frame_span(s, template)
    block = build(s[ta:tz], **kw)
    aa, az = _frame_span(s, after)
    s = s[:az] + '\n\n  <!-- ══════════════════ %s · %s ══════════════════ -->\n  ' % (kw['n'], kw['name'].upper()) + block + s[az:]
    open(path, 'w', encoding='utf-8').write(s)
    return kw['id']
