# -*- coding: utf-8 -*-
"""Key fixes per screen, shown as tags on each before/after card.

Two to five per card, each naming a concrete change — not "improved layout".
Where the live app never rendered the screen at all, NEW carries the reason.
"""
TAGS = {
 'quotes':              ['Two filter mechanisms merged into one', 'Money KPIs become a summary, not a filter', 'Validity and proforma state their unit'],
 'quotes-empty':        ['The only state production has rendered', 'Says what a quotation is for', 'One way to start'],
 'customers':           ['Bulk bar for checkboxes that did nothing', 'Rows-per-page control added', 'All 8 columns kept'],
 'customer-record':     ['5 record tabs live on the record, not the index', '11 profile fields kept', 'Merge review surfaced'],
 'opportunity-drawer':  ['"The task was due ." null date fixed', 'Raw enum whatsapp_call made human', '"Stageproposal Sent" spaced correctly', 'One header, one close'],
 'front-desk':          ['Real Veerha arrival, not only "booked elsewhere"', '44-word disclaimer said once, not 12 times', 'Room number is the largest element', 'Both status axes shown together'],
 'touchpoints':         ['Channels + Other = total, on every row', 'KPI strip drawn as the equation', '"Other" named: notes, forms, qualification', 'Scope stated: 19 of 22 touched'],
 'touchpoint-drawer':   ['Every event carries its class', 'Six "Other" broken into its parts'],
 'booking-links':       ['Toggle matches the page’s own words', 'One entry per human, not duplicates', 'Jargon leak "across the agency" removed'],
 'booking-links-empty': ['Empty state designed', 'Says what a bookable person is'],
 'workflows':           ['"step 9 of 8" fixed — one denominator', 'Failure vocabulary added', 'Waiting runs say what they wait for'],
 'employee-new':        ['25 config chips given plain names', 'Scope checkboxes use one spelling'],
 'hire':                ['"Coming soon" states what is missing', 'Seat cost shown per hire'],
 'knowledge':           ['Taxonomy conflict stated, not hidden', '6 kinds and 11 collections both drawn'],
 'memory':              ['Credential memory quarantined and masked', '43 identical rows collapse to one', 'Five scopes spelled one way', 'Empty scopes explain what belongs'],
 'calling':             ['Engine voice IDs removed', 'Attempted vs dialled reconciled', 'Save bar states unsaved changes'],
 'deliveries':          ['One verdict column: reached / nobody / failed', 'Adapter and rows read one field', 'Live vs test grouped and explained'],
 'deliveries-failed':   ['NEW — no failure existed to copy', '100 of 100 were "ok" in production'],
 'properties':          ['Channel-manager sync made visible', 'Two live screens folded into one noun switch'],
 'shared-resources':    ['Grey bar becomes a real chart', '"One of them is" column added'],
 'resource-drawer':     ['Worst field relabelled to its real meaning', 'Derived total vs daily cap settled'],
 'pricing':             ['Populated — production has never shown one', '"1 row held back" with the reason', 'Save outranks Sync now', 'Key masked with Replace'],
 'pricing-empty':       ['States what staying empty costs', '11 leads asked about price this month'],
 'departments':         ['Linked to reporting lines, which drive visibility'],
 'fields':              ['Impossible fill statistic replaced', 'Two populations, each with a denominator', 'Dead guest questions called dead', 'Seven types in plain language'],
 'fields-profiles':     ['NEW — never captured before', 'Qualification is settling a topic, not filling boxes', 'The order is the order it asks in'],
 'fields-changelog':    ['NEW — never captured before', 'Says there is nothing to roll back to', 'Person vs system actor'],
 'forms':               ['Type is read-only — set in Fields', 'Preview matches the list beside it', '"Money" resolved to a display option'],
 'automation':          ['Stages and the thresholds that move them, together', 'Two live screens merged'],
 'developers':          ['Key masked, with rotate and revoke', 'Credential moved out of the URL to a header', 'All four keys state transport and lifecycle'],
 'developers-empty':    ['Production state: "No key yet"', 'Verify-token error promoted to the top'],
 'billing':             ['One coherent price, not ₹0 and ₹85,000', '999-seat sentinel becomes a real limit', 'Paused employee still holds a seat', 'Usage dated and projected'],
 'billing-empty':       ['Invoices empty state designed', 'No "charged to card" beside "no card"'],
 'wallet':              ['All 24 credit rows kept', 'Near-duplicate rows made distinguishable', 'Ledger names a price-list item exactly'],

 'dashboard':        ['Answers five questions in order', 'Decisions surfaced, not buried', 'Overnight work made visible', 'One accent colour'],
 'dashboard-loading':['NEW — no loading state existed', 'Skeletons hold the final shape', 'No layout jump on load'],
 'analytics':        ['Every chart states its conclusion', 'One series colour', 'Denominator on every figure', 'Charts carry aria-labels'],
 'leads':            ['Scope tiles double as filters', 'Veerha’s Read as a column', 'Recommended next step inline', 'Score given a denominator'],
 'lead-drawer':      ['List stays readable behind', 'Evidence split ✓ / ⚠', 'Next step paired with its reason', 'Facts block, not a form dump'],
 'leads-queue':      ['NEW — a real re-sort, not a filter', 'Overdue first, then score', 'Action travels with the row'],
 'leads-empty':      ['NEW — empty state designed', 'Says what, why and what next', 'No dead-end blank table'],
 'leads-error':      ['NEW — channel error state', 'Data still usable beneath', 'Error sits above the list, not over it'],
 'contacts':         ['Same template, different nouns', 'Tab strip replaces filter bar', 'Consent status made visible'],
 'segments':         ['Yours vs Veerha’s, separated', 'Each preset states its size', 'Own empty state'],
 'import':           ['One question per step', 'Consent step cannot be skipped', 'Mapping previewed before commit'],
 'capture':          ['The A5 shape the other 18 inherit', 'Live preview beside the form', 'Embed snippet copyable'],
 'opportunities':    ['Stage replaces temperature', 'Value column aligned, not mono', 'Ageing shown per deal'],
 'pipeline':         ['NEW — advertised but never rendered', 'Column totals and counts', 'Bar widths derived, not eyeballed'],
 'proposal':         ['Only ever rendered empty before', 'Basket priced as you build', 'Margin shown against policy'],
 'bookings':         ['Month grid answers one question', 'Arrival counts per day', 'No calendar/list ambiguity'],
 'booking-detail':   ['NEW — only the empty variant existed', 'Payment state stated plainly', 'Guest history in place'],
 'inbox':            ['Says who is answering', 'Handover reason given', 'Context panel beside the thread'],
 'inbox-taken':      ['NEW — takeover state', 'Unmissable state change', 'Prevents two people replying'],
 'channels':         ['Disconnected channel treated as an outage', 'States the cost in leads', 'Fix is one button'],
 'templates':        ['List is the palette, form the inspector', 'Compliance rule stated up front', 'Approval status per template'],
 'mail':             ['Folder rail added inside the shell', 'Same inbox grammar reused', 'Thread and context side by side'],
 'email-studio':     ['Canonical three-column builder', 'Blocks, canvas, inspector', 'Inspector shown populated'],
 'tasks':            ['Grouped by when, not by type', 'Overdue separated out', 'Each row carries its action'],
 'review':           ['Every row is a decision Veerha held', 'Reason shown with the item', 'Approve/▸edit in place'],
 'callbacks':        ['Empty queue framed as a good outcome', 'Same template, no special case'],
 'calendar':         ['Booked left, free right', 'Answers both calendar questions', 'Slot lengths visible'],
 'hours':            ['Records edited in place', 'Hours framed as a promise, not a preference', 'Gaps flagged'],
 'recommendations':  ['Three live screens folded into one', 'Noun becomes a badge', 'Evidence on every card'],
 'campaign-builder': ['One offer, three channels', 'WhatsApp state stated honestly', 'Stepper shows all five stages'],
 'sequences':        ['3 of 4 steps never sent — stated once', 'Cause and count given', 'Fix offered as a button', 'Moved out of Settings'],
 'landing-pages':    ['Inspector shown populated', 'Blocks palette on the left', 'Lead form treated as the point'],
 'creative-studio':  ['No palette — nothing to drag', 'Size moved above the canvas', 'Colour read from brand settings'],
 'attribution':      ['Live version is all zeros', 'ROAS blank where spend is missing', 'Duplicate source rows merged', 'Conclusion stated on the chart'],
 'employees':        ['Broken employee says so first', 'Three figures, never more', 'Scope written in plain words'],
 'workflow':         ['NEW — never rendered', 'Vertical spine, not a free canvas', 'Breakage shown in place'],
 'catalogs':         ['Completion meter is the point', 'Each gap states its cost', 'Silent failure made loud'],
 'property-wizard':  ['Nine steps moved to a side rail', 'Progress always visible', 'Save and resume'],
 'org-chart':        ['Tree has never rendered before', 'AI employees on the chart', 'Dashed = supervises an AI', 'Health visible from the top'],
 'org-empty':        ['The state the live app is in', 'Explains why nothing draws', 'Two ways out offered'],
 'team':             ['Stale invitation surfaced', 'Roles stated as reach', 'Points to where AI permissions live'],
 'onboarding':       ['A transcript, not a form', 'States what your sentence will configure', 'Skippable with defaults'],
 'brand':            ['Tab strip carries four sibling screens', 'Live preview of guest-facing pages', 'One save bar'],
 'ai-behaviour':     ['Every control states its consequence', 'Autonomy bounded explicitly', 'Discount ceiling made concrete'],
 'system':           ['Raw config keys replaced with plain language', 'Status before settings', 'Dangerous actions separated'],
 'states':           ['Four failures on one screen', 'Replaces a bare "Not authorised" bar', 'Says who can grant access'],
 'login':            ['Claims are measured, not marketing', 'Single template for six screens', 'OAuth offered alongside'],
 'register':         ['Asks what you run first', 'Skips questions later because of it', 'Two minutes, stated'],
 'forgot-password':  ['Says it works once', 'States the expiry', 'One way back'],
 'reset-password':   ['Validation as you type', 'Primary disabled until valid', 'Live app had no field validation'],
 'activate':         ['Bare error replaced', 'Confirms nothing was damaged', 'Two ways out'],
 'auth-callback':    ['NEW — never captured', 'Makes a slow handshake look deliberate', 'Escape hatch if it stalls'],
 # --- Bucket D · the ten guest pages (archetype A12) ---------------------------
 # These have no "before": two of the routes do not resolve in production at all,
 # and the pages that do resolve show a real customer's booking, which does not
 # leave the audit folder. Each tag says what the page had to get right.
 'public-enquiry-form':    ['NEW — field set from the live form, layout designed', 'Thirteen fields, three above the fold', 'Child ages appear only when a child is coming'],
 'quotation-view-respond': ['NEW — /q/ has no page yet', 'Price and expiry outrank everything', '"Ask a question" weighted equal to accepting'],
 'proposal-rooms-confirm': ['NEW — /p/ is empty in production', 'The alternative room is shown, not hidden', 'One page, one confirm'],
 'meeting-booking':        ['NEW — "No bookable people yet"', 'Timezone named, not assumed', 'Only genuinely free slots are listed'],
 'reschedule-cancel':      ['NEW — never rendered', 'What is booked stays visible while you move it', 'Cancel is present and quiet'],
 'stay-hub':               ['Structure verified against the live page', 'Answers what, when, where before asking anything', 'Live version made everything equally important'],
 'online-check-in':        ['Collects what the front desk says it "holds nothing" of', 'The allergy answer states that it routes to the kitchen', 'Documents say how long they are kept'],
 'preferences-consent':    ['Eleven fields sat at 0% filled', 'Every question carries the reason it is asked', 'Consent split into three separate answers'],
 'rate-your-stay':         ['NEW — the route falls through to marketing today', 'Follow-up depends on the score', 'Private note never passed off as public'],
 'terminal-states-thank-you-expired-actioned': ['Expired copy kept verbatim — the product had it right', 'Two of three currently show the marketing site', 'Never a dead end, never an unasked-for redirect'],
}
